if(EXISTS "/home/runner/work/serialstorm/serialstorm/build-cov/tests/test_serialstorm-b12d07c_tests.cmake")
  include("/home/runner/work/serialstorm/serialstorm/build-cov/tests/test_serialstorm-b12d07c_tests.cmake")
else()
  add_test(test_serialstorm_NOT_BUILT-b12d07c test_serialstorm_NOT_BUILT-b12d07c)
endif()
